theme: minima
name: vj4anc
title: VJ for ANC 5C07
google_analytics: G-LGDE2KRY1D
header_pages:
  - vj.md
  - 5c07.md
  - ancs.md
  - positions.md
  - issues.md
minima:
  social_links:
    twitter: vjkapur
    github: vjkapur
